imports:
- path: project.py

resources:
# The "name" property below will be the name of the new project
- name: lcg-cloudservices-prod
  type: project.py
  properties:
    # Change this to your organization ID.
    organization-id: "500829983291"
    # Change the following to your organization's billing account
    billing-account-name: billingAccounts/00BC3C-C82403-19C651
    # The apis to enable in the new project.
    # To see the possible APIs, use gcloud CLI: gcloud service-management list
    apis:
    - compute.googleapis.com
    - deploymentmanager.googleapis.com
    - pubsub.googleapis.com
    - storage-component.googleapis.com
    - monitoring.googleapis.com
    - logging.googleapis.com
    - iam.googleapis.com
    # The service accounts you want to create in the project
    service-accounts:
    - my-service-account-1
    - my-service-account-2
    bucket-export-settings:
      create-bucket: true
      # If using an already existing bucket, specify this
      # bucket: <my bucket name>
    # Makes the service account that Deployment Manager would use
    # in the generated project an admin
    set-dm-service-account-as-owner: true
    # IAM policy on the new project
    iam-policy:
      bindings:
      - role: roles/owner
        members:
        # NOTE: The DM service account that is creating this project will
        # automatically be added as an owner.
        # Add any accounts you want to have access
        - user:andrew.burke@ladbrokescoral.com
      - role: roles/viewer
        members:
        - user:russell.clare@ladbrokescoral.com
